#Print a square of stars of size 5
print("* * * * * * * * * *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("*                 *")
print("* * * * * * * * * *")
